name: Build OpenCV-Mobile for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Ninja and CMake
        run: sudo apt-get update && sudo apt-get install -y ninja-build cmake

      - name: Download Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip -d $HOME/ndk
          echo "ANDROID_NDK=$HOME/ndk/android-ndk-r25c" >> $GITHUB_ENV

      - name: Download OpenCV source
        run: |
          wget -q https://github.com/opencv/opencv/archive/4.10.0.zip -O opencv-4.10.0.zip
          unzip -q opencv-4.10.0.zip
          mv opencv-4.10.0 opencv

      - name: Apply patches
        working-directory: opencv
        run: |
          patch -p1 -i ../patches/opencv-4.10.0-no-zlib.patch

      - name: Create build directory
        run: mkdir -p build-${{ matrix.abi }}

      - name: Configure CMake for ${{ matrix.abi }}
        working-directory: build-${{ matrix.abi }}
        env:
          ANDROID_ARM_NEON: ${{ matrix.abi == 'armeabi-v7a' && 'ON' || 'OFF' }}
        run: |
          cmake \
            -G "Ninja" \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.abi }} \
            -DANDROID_PLATFORM=android-21 \
            -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=False \
            -DANDROID_CPP_FEATURES="no-rtti no-exceptions" \
            -DANDROID_ARM_NEON=$ANDROID_ARM_NEON \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCMAKE_BUILD_TYPE=Release \
            $(cat ../opencv4_cmake_options.txt) \
            -DBUILD_opencv_world=OFF \
            -DOPENCV_DISABLE_FILESYSTEM_SUPPORT=ON \
            -DOPENCV_EXTRA_FLAGS="-mno-outline-atomics" \
            -DOPENCV_SKIP_ANDROID=ON \
            -DBUILD_opencv_calib3d=ON \
            -DBUILD_opencv_core=ON \
            -DBUILD_opencv_imgproc=ON \
            -DBUILD_opencv_features2d=ON \
            -DBUILD_opencv_flann=ON \
            ..

      - name: Build with Ninja
        working-directory: build-${{ matrix.abi }}
        run: ninja -j$(nproc)

      - name: Install libraries
        working-directory: build-${{ matrix.abi }}
        run: ninja install

      - name: Package libraries
        working-directory: build-${{ matrix.abi }}
        run: |
          zip -r opencv-mobile-4.10.0-android-${{ matrix.abi }}.zip install

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opencv-mobile-4.10.0-android-${{ matrix.abi }}
          path: build-${{ matrix.abi }}/opencv-mobile-4.10.0-android-${{ matrix.abi }}.zip
